import React, { useEffect, useState } from 'react';
import './Sidebar.scss';

export default function Sidebar({
  query,
  onQueryChange,
  tags,
  selectedTag,
  onTagSelect,
}: {
  query: string;
  onQueryChange: (v: string) => void;
  tags: string[];
  selectedTag: string | null;
  onTagSelect: (t: string | null) => void;
}) {
  const [local, setLocal] = useState(query);

  // keep local input in sync when parent clears
  useEffect(() => {
    setLocal(query);
  }, [query]);

  // debounce sending value back to parent
  useEffect(() => {
    const id = setTimeout(() => onQueryChange(local), 300);
    return () => clearTimeout(id);
  }, [local]);

  return (
    <div className="sidebar">
      <div className="sidebar-header">
        <img src="../src/assets/recipository-logo-white.png" alt="Logo" className="sidebar-logo"/>
        <div className="sidebar-title">
          <h3>Recipository</h3>
          <div className="sidebar-subtitle">The Recipe Repository</div>
        </div>
      </div>

      <div className="sidebar-search">
        <input
          className="sidebar-search-input"
          type="search"
          placeholder="Search recipes..."
          value={local}
          onChange={(e) => setLocal(e.target.value)}
        />
        {local ? (
          <button
            type="button"
            className="sidebar-clear"
            aria-label="Clear search"
            onClick={() => {
              setLocal('');
              onQueryChange('');
              onTagSelect(null);
            }}
          >
            ×
          </button>
        ) : null}
      </div>

      {tags && tags.length > 0 && (
        <div className="tag-list">
          {tags.map((t) => {
            const active = selectedTag === t;
            return (
              <button
                key={t}
                type="button"
                className={`tag-chip ${active ? 'active' : ''}`}
                onClick={() => onTagSelect(active ? null : t)}
              >
                {t}
              </button>
            );
          })}
        </div>
      )}


    <div className="sidebar-footer">
      <p>Logo generated by Chat GPT</p>
    </div>
    </div>
  );
}